[project]
name = "mpmmine"
version = "0.1.01.20260722"
authors = [
    { name = "Tomasz P. Pawlak", email = "tpawlak@cs.put.poznan.pl" },
    { name = "Rafał Stachowiak", email = "rstachowiak@cs.put.poznan.pl" }
]
description = "A Python package for accessing the MPMMine dataset"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*", "ACKNOWLEDGMENTS.md"]
dependencies = []

[project.optional-dependencies]
sevenzip = ["py7zr"]
test = [
    "pytest>=8.0.0",
]

[project.urls]
Homepage = "https://github.com/MPMMine/mpmmine-py"
Repository = "https://github.com/MPMMine/mpmmine-py.git"
Issues = "https://github.com/MPMMine/mpmmine-py/issues"
Dataset = "https://github.com/MPMMine/MPMMine"

[tool.hatch.build.targets.wheel]
packages = ["src/mpmmine"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
